force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Оферта</label>
    <nameField>
        <displayFormat>ON-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/NDS__c.field-meta.xml
<CustomField>
    <fullName>NDS__c</fullName>
    <label>Применяемая ставка НДС</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20%</fullName>
            </value>
            <value>
                <fullName>Не облагается</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/classes/YandexEdaOfferController.cls
/**
 * Created by user on 12.09.2019.
 */

public with sharing class YandexEdaOfferController {
    public Offer__c offer { get; set; }

    public List<SelectOption> getTypes() {
        Schema.sObjectType sobject_type = Offer__c.getSObjectType();
        Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe();
        Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap();
        List<Schema.PicklistEntry> pick_list_values = field_map.get('NDS__c').getDescribe().getPickListValues();
        List<selectOption> options = new List<selectOption>();

        for (Schema.PicklistEntry a : pick_list_values) {
            options.add(new selectOption(a.getLabel(), a.getValue()));
        }
        return options;
    }
}